version: '3.8'

services:
  angular-app:
    image: node:16-alpine
    container_name: angular-app
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./fe:/app

  laravel-app:
    image: php:8.2-fpm
    container_name: laravel-app
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./be:/var/www
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_DATABASE=your-database
      - DB_USERNAME=your-username
      - DB_PASSWORD=your-password
