services:
  angular:
    container_name: network-fe
    build:
      context: ./fe  # Path alla directory che contiene il Dockerfile per Angular
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    container_name: network-be
    build:
      context: ./be  # Path alla directory che contiene il Dockerfile per il backend
      dockerfile: Dockerfile
    expose:
      - "9000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
